name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git User
        run: |
          git config --global user.name 'ashwinkshenoy'
          git config --global user.email 'ashwinkshenoy@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ashwinkshenoy/vue-simple
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Checkout and Pull Branch
        run: git checkout "${GITHUB_REF:11}" && git pull origin master

      - name: Install All Packages & Version
        run: |
          npm run lerna:bootstrap

      - name: Build All Packages
        run: npm run lerna:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}

      - name: Authenticate with Registry
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Packages
        run: |
          npm run lerna:version
          npm run lerna:publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
